### ISSUE TITLE
Unexpected input 'args', valid inputs are ['']

### ISSUE THREAD

**Issue by ellisio** [teamnovu/vapor-action#3]
Using the following config:

```
- name: Deploy to Staging
  env:
    VAPOR_API_TOKEN: ${{ secrets.VAPOR_API_TOKEN }}
    GITHUB_SECRET: ${{ secrets.ELLISIO_TOKEN }}
  uses: teamnovu/vapor-action@v1.0.3
  with:
    args: deploy staging
```

I get the following warning in our build:

```
##[warning]Unexpected input 'args', valid inputs are ['']
Run teamnovu/vapor-action@v1.0.3
  with:
    args: deploy staging
```

Is it possible the syntax is no longer valid with changes to GitHub actions?
