### ISSUE TITLE
Environment for using docker deployments

### ISSUE THREAD

**Issue by BoyeMagnus** [teamnovu/vapor-action#5]
When setting: `runtime: docker` in the vapor.yml file, then docker is required on the building machine.

Would it be possible to support this?

Read more here:
https://blog.laravel.com/vapor-docker-based-deployments

**Comment by Neodark7** [comment]
+1 on that

**Comment by andrewandante** [comment]
Hi team, I've just encountered the same. I basically had to do it manually instead, like so:

```yml
name: Vapor Deploy
concurrency: vapor
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1
        tools: composer:v2
        coverage: none
    - name: Require Vapor CLI
      run: composer global require laravel/vapor-cli
    - name: Install Project Dependencies
      run: composer install --no-interaction --prefer-dist --optimize-autoloader
    - name: Deploy to darkroom
      env:
        VAPOR_API_TOKEN: ${{ secrets.VAPOR_API_TOKEN }}
      run: vapor deploy production
```

And it worked just fine.
